### ISSUE TITLE
Article Tags Doesn't Show in Article Page in Chrome 62

### ISSUE THREAD

**Issue by rezamajidi** [smashingmagazine/redesign#323] opened 2017-12-04 08:31 UTC
**- Do you want to request a *feature* or report a *bug*?**

**- What is the current behavior?**

**- If the current behavior is a bug, please provide the steps to reproduce.**

**- What is the expected behavior?**

**- Please mention your operating system version and the version of your browser**

**Comment by rezamajidi** [comment] 2017-12-04 08:33
![chrome62](https://user-images.githubusercontent.com/7690415/33543130-158e480c-d8eb-11e7-8061-a8bf8cfd2564.JPG)

**Comment by vitalyfriedman** [comment] 2017-12-04 16:52
Could you specify your OS, please? @rezamajidi

**Comment by rezamajidi** [comment] 2017-12-05 11:00
I was using Win7 and now this problem has gone in Win10

**Comment by vitalyfriedman** [comment] 2017-12-05 23:50
Interesting. The issue is still not resolved though. Closing this one as it's a duplicate of https://github.com/smashingmagazine/redesign/issues/318.

Thanks for reporting the issue, @rezamajidi!

**Closed as completed by vitalyfriedman** 2017-12-05 23:50 UTC
