### ISSUE TITLE
Article header positioning bug in Firefox 57 (Responsive, 1008px+)

### ISSUE THREAD

**Issue by chrisheninger** [smashingmagazine/redesign#305] opened 2017-11-28 18:09 UTC
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
`.article__header` on `https://www.smashingmagazine.com/design-systems-book/` in Firefox are positioned incorrectly when the viewport is sized at over 1008px.
<img width="1314" alt="screen shot 2017-11-28 at 11 05 01 am" src="https://user-images.githubusercontent.com/5051745/33336113-2f9e5fde-d42c-11e7-968f-7a064b5c1ba5.png">

**- Please mention your operating system version and the version of your browser**
Mac OS X (latest) with Firefox 57 (latest)

**Comment by vitalyfriedman** [comment] 2017-11-29 23:04
Unfortunately I couldn't reproduce it at all @chrisheninger — could you try again?..

**Comment by chrisheninger** [comment] 2017-11-30 21:57
Still broken in Firefox for me. My assumption about `.article__header` was wrong– after taking a closer look it's something to do with the way Firefox is handling the `:before` block and the paragraph that is supposed to be wrapping around it.

<img width="883" alt="screen shot 2017-11-30 at 2 47 19 pm" src="https://user-images.githubusercontent.com/5051745/33456936-2e48feec-d5de-11e7-9042-1b679d0cf1e5.png">

Adding a `display: none;` to the `.drop-caps` fixes it, but you lose the cute illustration. :(

<img width="1253" alt="screen shot 2017-11-30 at 2 54 38 pm" src="https://user-images.githubusercontent.com/5051745/33457055-849e3d7a-d5de-11e7-967e-910d928d30f2.png">

**Comment by vitalyfriedman** [comment] 2017-11-30 22:13
Very strange. Still trying to fix the bug. Seems to be a weird one @chrisheninger

**Comment by chrisheninger** [comment] 2017-12-02 04:16
Good news... it's fixed! Not sure if something happened on your end or if FF updating to 57.0.1 fixed it... but looks nice now. :)

<img width="1307" alt="screen shot 2017-12-01 at 9 13 20 pm" src="https://user-images.githubusercontent.com/5051745/33511687-89f6b0fa-d6dc-11e7-8c71-d842bfbffe50.png">

I'll let you handle closing. 👍

**Comment by vitalyfriedman** [comment] 2017-12-05 23:52
Hummm... Not so happy about magic solutions to problems... Closing for now, but will keep an eye in case it appears again. Thanks for reporting the issue, dear @chrisheninger!

**Closed as completed by vitalyfriedman** 2017-12-05 23:52 UTC
