### ISSUE TITLE
URL of a single post doesn't update when scrolling to the next one

### ISSUE THREAD

**Issue by KimBranzell** [smashingmagazine/redesign#68] opened 2017-03-17 11:02 UTC
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
URL doesn't get updated on single blog posts when scrolling to the next article, but stays the same throughout. This can make sharing the subsequent blog posts by copy-pasting said URL difficult.

**- If the current behavior is a bug, please provide the steps to reproduce.**
Click on an a blog post and scroll to the next by scrolling to the very bottom of the first post.

**- What is the expected behavior?**
URL should somehow update to reflect the current viewed post.

**- Please mention your operating system version and the version of your browser**
MacOS Sierra 10.12.3.
Chrome 56.0.2924.87 (but I also had the same result on Firefox 52, Safari 10.0.3 and Opera 43.0).

**Comment by anselmh** [comment] 2017-03-17 11:28
Duplicate of #35?

**Comment by KimBranzell** [comment] 2017-03-17 12:03
Ah, yeah, it is. Closing this!

**Closed as completed** 2017-03-17 12:04 UTC
