### ISSUE TITLE
Cannot highlight text covered by avatar/title/meta area on news articles

### ISSUE THREAD

**Issue by andyfitch** [smashingmagazine/redesign#69] opened 2017-03-17 11:33 UTC
Bug: on news articles, the first paragraph is not highlightable, as it is covered by the div containing the article title/avatar/metadata.

Steps to reproduce:
- Visit: https://next.smashingmagazine.com/2017/02/art-calligraphy-getting-started-lessons-learned/
- Try to highlight first paragraph

Expected behaviour:
Text highlights

Actual behaviour:
The focus is on the title area, which can be highlighted by moving your mouse to the right.

Browser: Latest desktop Chrome

**Comment by vitalyfriedman** [comment] 2017-03-18 22:57
Good point, @andyfitch — looking into it.

**Comment by vitalyfriedman** [comment] 2017-03-18 22:58
Closing as it's a duplicate of #22.

**Closed as completed by vitalyfriedman** 2017-03-18 22:58 UTC
