### ISSUE TITLE
Quick Summary showing shortcode, and not its intended image

### ISSUE THREAD

**Issue by leoloso** [smashingmagazine/redesign#259] opened 2017-11-22 10:47 UTC
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
The quick summary is showing a shortcode where there should be an image. I guess either the image should be shown, or the shortcode ignored from the Quick Summary. Check screenshot below

**- If the current behavior is a bug, please provide the steps to reproduce.**
URL: https://www.smashingmagazine.com/2017/10/service-worker-single-page-application-wordpress-sites/
![screenshot-2017-11-22 implementing a service worker for single-page app wordpress sites 2](https://user-images.githubusercontent.com/1981996/33123484-53a46e58-cfb5-11e7-8c7d-7fb98953eb34.png)

**Comment by vitalyfriedman** [comment] 2017-11-30 23:44
The issue is fixed now. Still, have to adjust the styling of tables. On it, dear @leoloso!

**Closed as completed** 2017-12-06 00:49 UTC
