### ISSUE TITLE
Firefox freezes when opening RSS feed

### ISSUE THREAD

**Issue by chriskirknielsen** [smashingmagazine/redesign#327] opened 2017-12-05 14:09 UTC
Hello there,

I have a bit of an issue with Firefox (57.0 on macOS Sierra) concerning the RSS feed from Smashing Magazine.
I have it saved is as a dynamic bookmark, but every time I try to load it (= hover the bookmark to open the list of articles), Firefox freezes for a few seconds. The list of articles shows up after a shirt while.

I fear this is an issue related to the number of links in the RSS feed. I have to scroll over a dozen "pages" of 50+ links to get to the bottom of the list.

Suggested action: reduce number of links in the RSS feed.

Thanks!

**Comment by lembitk** [comment] 2017-12-05 21:14
Related to / duplicate of #321.

**Comment by vitalyfriedman** [comment] 2017-12-05 23:25
The fix is being deployed @lembitk @chriskirknielsen — thanks for reporting it!

**Closed as completed** 2017-12-06 01:03 UTC
Labels: bug, fix-being-deployed
